---
title: "Markdown basics"
author: "Reinhard Simon"
date: '2019-03-06'
output:
  html_document: default
  word_document: default
  pdf_document: default
bibliography: references.bib
---

# Introduction

Markdown provides an easy way to write formatted text like

- *italics*
- **bold**
- `code`
- superscript^2^
- H~2~O
- SO~4~^2-^
- [links](http://google.com)

You can also use it for:

- equations $E = mc^2$

- and bibliographies [@darwin2004origin]

# Results

```{r echo=FALSE}
knitr::kable(summary(cars))
```


```{r table0}
library(magrittr)
cars %>% summary %>% knitr::kable()
```


```{r echo=FALSE}
plot(cars$speed, cars$dist, type = "l", lwd = "2", col = "blue")
```

The number of records in the database is `r nrow(cars)`.

# Results on the IRIS database

```{r}
knitr::kable (summary(iris))
```


```{r}
data(iris)
iris %>% summary %>% knitr::kable()
```

```{r echo=FALSE}
plot(iris$Species, iris$Petal.Length, type = "l", col = "orange")
```

```{r echo=FALSE}
plot(iris$Species, iris$Petal.Width, type = "l", col = 3)
```


# Session Information

```{r}
sessionInfo()
```


# References



